# ansible/inventory/hosts.yml
# Terraform output の EIP を記入すること
all:
  children:
    dev:
      hosts:
        fivem-dev:
          ansible_host: "{{ lookup('env', 'DEV_SERVER_IP') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/fivem-dev.pem
    prd:
      hosts:
        fivem-prd:
          ansible_host: "{{ lookup('env', 'PRD_SERVER_IP') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/fivem-prd.pem
